### ISSUE TITLE
Error in install procedure

### ISSUE THREAD

**Issue by deKeijzer** [joselado/quantum-lattice#2]
Hi there, 

That's a very nice looking package! I've tried to get it to run on my system by following the steps

`git clone https://github.com/joselado/quantum-lattice`
`python install.py`

But one I execute the program

`quantum-lattice`

I get the following; 

` briandekeijzer@MacBook-Pro ~ % quantum-lattice 
Traceback (most recent call last):
  File "/Users/briandekeijzer/quantum-lattice/bin/../bin/versions/quantum-lattice-pyqt", line 15, in <module>
    from interfacetk import qtwrap # im port the library with simple wrappers to pyqt
  File "/Users/briandekeijzer/quantum-lattice/bin/versions/../..//pysrc/interfacetk/qtwrap.py", line 15, in <module>
    import numpy as np
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/core/multiarray.py", line 1132
    def putmask(a, /, mask, values):
                   ^
SyntaxError: invalid syntax`

Perhaps it's a environment related issue. I am running Python3.9 and numpy 1.26.4 on a Apple M3 chip.

**Comment by joselado** [comment]
Hi deKeijzer,

thanks for the kind feedback and the message. It seems that the issue may be with the Python version Mac has (it seems that the code is trying to use the homebrew version).

You can try to install Anaconda Python, and put that Python on your bash path (so that when you write "which python" in a terminal the output refers to the Anaconda one)
https://www.anaconda.com/download

Best regards,
Jose
